### ISSUE TITLE
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system

### ISSUE THREAD

**Issue by P8ntBal1551** [thrnz/docker-wireguard-pia#30]
I have privileged mode enabled, net_admin and sys_module capabilities are on, and the environment variables

```
USER=*Redacted*
LOCAL_NETWORK=192.168.1.0/24
PASS=*Redacted*
LOC=*Redacted*
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PIA_IP=*Redacted*
PIA_PORT=1337
PIA_CN=*Redacted*
VPNDNS=8.8.8.8, 8.8.4.4
FIREWALL=0
```

Here is my startup log

```
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go wg0
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add *Redacted* dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] iptables-restore -n

interface: wg0
  public key: *Redacted*
  private key: (hidden)
  listening port: 49302
  fwmark: 0xca6c

peer: *Redacted*
  endpoint: *Redacted*:1337
  allowed ips: 0.0.0.0/0

Mon Sep 13 16:50:24 UTC 2021: WireGuard successfully started
Mon Sep 13 16:50:24 UTC 2021: Adding route to 192.168.1.0/24
```
Even though it says it started successfully, I can't ping out to anything, and when I put a port forward on it, it times out trying to pull the port number.

I am running CentOS 8 with kernel 4.18 (I should update that)

Thank you

**Comment by thrnz** [comment]
I'm not sure what the problem might be, but that particular error message might be a red herring as it can show up even when the container is working as expected. I should probably fix that.

I'm not actually sure what `src_valid_mark` does as I could only find limited info about it when looking in the past. `wg-quick` [tries to set it to 1](https://github.com/WireGuard/wireguard-tools/blob/3ba6527130c502144e7388b900138bca6260f4e8/src/wg-quick/linux.bash#L240) when adding the default route, and dies when unable to do so (even if it's already set to 1).

Running the container as privileged usually fixes it - IIRC there might be some further weirdness if host networking is used -  though it seems that's not working in your case. Running as privileged isn't needed if `net.ipv4.conf.all.src_valid_mark=1` is set using the container's [sysctls](https://github.com/compose-spec/compose-spec/blob/master/spec.md#sysctls) instead. I've [modified](https://github.com/thrnz/docker-wireguard-pia/blob/d43c544ad3aea7f8aef58894c7417db2cc3bc09e/Dockerfile#L13) `wg-quick` so it doesn't die when this happens, but the error message still shows even in an otherwise working container with it manually set to 1.

**Comment by P8ntBal1551** [comment]
I don't know why this happened, but I tried it again today with the exact same settings and everything was working. Sorry for bothering you with this. I'll close it
