### ISSUE TITLE
Dedicated IP

### ISSUE THREAD

**Issue by samcro1967** [thrnz/docker-wireguard-pia#35]
Will support be added for the Dedicated IP offering from PIA?  Or maybe it is already there and I am just missing it.

**Comment by thrnz** [comment]
I don't think it's possible to use a dedicated IP with this container atm.

I'd probably consider adding support once its added to their own [standalone scripts](https://github.com/pia-foss/manual-connections/issues/84), though as it's not something I use myself I'm not too keen on diving back into the source to their desktop app to work out how it's done.

If someone else want's to investigate further then [this](https://github.com/pia-foss/desktop/blob/d408b4a2219019783547e1db281f46f9658d1dda/daemon/src/wireguardmethod.cpp#L1211) might be a good point to start from. It looks like basic http auth is used instead of a token on the query string when registering the wg pubkey which is simple enough to do. I'm not sure of the process of turning a token purchased from PIA for a dedicated IP into an actual ip address and cname though.
