### ISSUE TITLE
Failed to fetch dedicated ip server info. Response: HTTP Token: Access denied.

### ISSUE THREAD

**Issue by BastionNtB** [thrnz/docker-wireguard-pia#87]
Hey there, I'm attempting to get this container up and running, but I'm running into issues.

Here is my compose.

```docker
version: '3'
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            # Auth token is stored here
            - pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - pia-shared:/pia-shared
        cap_add:
            - NET_ADMIN
            # SYS_MODULE might not be needed with a 5.6+ kernel?
            #- SYS_MODULE
        # If the kernel module isn't available, mounting the tun device may be necessary for userspace implementations
        #devices:
        #  - /dev/net/tun:/dev/net/tun
        environment:
            # The following env vars are required:
            - USER=${USER}
            - PASS=${PASS}
            - PIA_DIP_TOKEN=${PIA_DIP_TOKEN}
            # The rest are optional:
            - LOCAL_NETWORK=${LOCAL_NETWORK}
            - VPNDNS=${VPNDNS}
            - PORT_FORWARDING=1
            - PORT_FILE_CLEANUP=0
            - FIREWALL=0
            - TZ=${TZ}
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 1.1.1.1 || exit 1
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    pia:
      external: true
    pia-shared:
      external: true
```

I'm passing these environment variables which are then referenced by the compose file. (Censored, of course)
```
USER='p########'
PASS='***********'
PIA_DIP_TOKEN='DIP*********************'
TZ='America/Los_Angeles'
VPNDNS='###.###.###.###'
LOCAL_NETWORK='###.###.###.###/24'
```

Here are the logs
```
Tue Dec 19 00:45:30 UTC 2023: Fetching dedicated ip server info
parse error: Invalid numeric literal at line 1, column 5
Tue Dec 19 00:45:31 UTC 2023: Failed to fetch dedicated ip server info. Response:
HTTP Token: Access denied.
Tue Dec 19 00:45:31 UTC 2023: Failed to generate WireGuard config
Tue Dec 19 00:45:31 UTC 2023: Fatal error
Tue Dec 19 00:45:42 UTC 2023: Shutting down WireGuard
wg-quick: `/etc/wireguard/wg0.conf' does not exist
```

Any help would be appreciated, thank you for the work you've done!

**Comment by thrnz** [comment]
Does the container work without the dedicated ip stuff set? You'll need to set the `LOC` env var to something and remove the `PIA_DIP_TOKEN` var to test it out.

That `HTTP Token: Access denied` error might suggest that the auth token (different to the DIP token itself) might not be being accepted for some reason, though I'm not sure. I think it throws a different error if the dip token itself was being rejected. There's currently no detection or recovery if that were to happen when using a DIP token, whereas the container generates a new auth token and retries if it happens when not using DIP stuff.

If that is the issue, then running the container once without a dedicated ip token set, or manually deleting the `/pia/.token` file might be enough to fix things. I could probably update the container to be able to recover by itself in future if that's whats going wrong.

**Comment by BastionNtB** [comment]
That seems to be the issue!

I swapped to LOC, reran it, all worked, swapped to DIP and it worked finally. So yeah, it seems it needs to auth before attempting to use the DIP token. Good catch.

**Comment by thrnz** [comment]
I've made a small change that means expired auth tokens should be picked up when using dedicated ips. If/when the auth token expires in future it should now be automatically regenerated as needed.

**Comment by BastionNtB** [comment]
Thank you!
